<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <NoWarn>1591</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="VirtoCommerce.Platform.Core" Version="3.1007.22" />
  </ItemGroup>
</Project>
